-- PayMux initial schema.
--
-- Conventions used throughout:
--   * Primary keys are prefixed ULIDs generated by the application
--     (internal/ids), stored as TEXT so they stay readable in logs and URLs.
--   * Monetary amounts are BIGINT in the currency's minor unit. For IDR that
--     is one rupiah, matching Midtrans's integer gross_amount.
--   * Gateway payloads live in JSONB with secrets stripped before storage.
--   * Timestamps are TIMESTAMPTZ and always written in UTC.

-- ---------------------------------------------------------------------------
-- Administrators and dashboard sessions
-- ---------------------------------------------------------------------------

CREATE TABLE admins (
    id            TEXT PRIMARY KEY,
    email         TEXT        NOT NULL,
    name          TEXT        NOT NULL DEFAULT '',
    password_hash TEXT        NOT NULL,
    disabled_at   TIMESTAMPTZ,
    last_login_at TIMESTAMPTZ,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Email uniqueness is case-insensitive without requiring the citext extension.
CREATE UNIQUE INDEX admins_email_key ON admins (lower(email));

CREATE TABLE admin_sessions (
    id         TEXT PRIMARY KEY,
    admin_id   TEXT        NOT NULL REFERENCES admins (id) ON DELETE CASCADE,
    token_hash TEXT        NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    user_agent TEXT        NOT NULL DEFAULT '',
    ip_address TEXT        NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX admin_sessions_admin_id_idx ON admin_sessions (admin_id);
CREATE INDEX admin_sessions_expires_at_idx ON admin_sessions (expires_at);

-- ---------------------------------------------------------------------------
-- Gateway accounts
--
-- Gateway credentials live here rather than on applications, so additional
-- gateways can be added without touching the application domain (PRD §59).
-- ---------------------------------------------------------------------------

CREATE TABLE gateway_accounts (
    id                   TEXT PRIMARY KEY,
    gateway              TEXT        NOT NULL,
    name                 TEXT        NOT NULL,
    environment          TEXT        NOT NULL CHECK (environment IN ('sandbox', 'production')),
    merchant_id          TEXT        NOT NULL DEFAULT '',
    client_key           TEXT        NOT NULL DEFAULT '',
    -- Sealed with AES-256-GCM by internal/crypto; never returned by the API.
    server_key_encrypted TEXT        NOT NULL,
    enabled              BOOLEAN     NOT NULL DEFAULT TRUE,
    is_default           BOOLEAN     NOT NULL DEFAULT FALSE,
    capabilities         JSONB       NOT NULL DEFAULT '{}'::jsonb,
    last_checked_at      TIMESTAMPTZ,
    last_check_ok        BOOLEAN,
    last_check_error     TEXT        NOT NULL DEFAULT '',
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX gateway_accounts_name_key ON gateway_accounts (lower(name));
CREATE INDEX gateway_accounts_gateway_idx ON gateway_accounts (gateway, enabled);

-- At most one default account per gateway and environment.
CREATE UNIQUE INDEX gateway_accounts_default_key
    ON gateway_accounts (gateway, environment)
    WHERE is_default;

-- ---------------------------------------------------------------------------
-- Applications, credentials and webhook destinations
-- ---------------------------------------------------------------------------

CREATE TABLE applications (
    id                 TEXT PRIMARY KEY,
    name               TEXT        NOT NULL,
    slug               TEXT        NOT NULL,
    description        TEXT        NOT NULL DEFAULT '',
    gateway_account_id TEXT        REFERENCES gateway_accounts (id) ON DELETE SET NULL,
    disabled_at        TIMESTAMPTZ,
    metadata           JSONB       NOT NULL DEFAULT '{}'::jsonb,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX applications_slug_key ON applications (lower(slug));

CREATE TABLE application_api_keys (
    id             TEXT PRIMARY KEY,
    application_id TEXT        NOT NULL REFERENCES applications (id) ON DELETE CASCADE,
    name           TEXT        NOT NULL DEFAULT '',
    mode           TEXT        NOT NULL CHECK (mode IN ('live', 'test')),
    -- SHA-256 of the full key. The plaintext is shown once, at creation.
    key_hash       TEXT        NOT NULL UNIQUE,
    display_prefix TEXT        NOT NULL,
    last_used_at   TIMESTAMPTZ,
    expires_at     TIMESTAMPTZ,
    revoked_at     TIMESTAMPTZ,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX application_api_keys_application_id_idx ON application_api_keys (application_id);

CREATE TABLE webhook_destinations (
    id               TEXT PRIMARY KEY,
    application_id   TEXT        NOT NULL REFERENCES applications (id) ON DELETE CASCADE,
    url              TEXT        NOT NULL,
    description      TEXT        NOT NULL DEFAULT '',
    -- Sealed HMAC signing secret for outbound deliveries.
    secret_encrypted TEXT        NOT NULL,
    -- Empty array means "all event types".
    event_types      TEXT[]      NOT NULL DEFAULT '{}',
    enabled          BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX webhook_destinations_application_id_idx ON webhook_destinations (application_id);

-- ---------------------------------------------------------------------------
-- Payments
-- ---------------------------------------------------------------------------

CREATE TABLE payments (
    id                     TEXT PRIMARY KEY,
    application_id         TEXT        NOT NULL REFERENCES applications (id) ON DELETE RESTRICT,
    gateway_account_id     TEXT        NOT NULL REFERENCES gateway_accounts (id) ON DELETE RESTRICT,
    gateway                TEXT        NOT NULL,

    -- The application's own reference, unique only within that application.
    application_order_id   TEXT        NOT NULL,
    -- The order id PayMux sends to the gateway; globally unique (PRD §22).
    gateway_order_id       TEXT        NOT NULL UNIQUE,
    gateway_transaction_id TEXT,

    amount                 BIGINT      NOT NULL CHECK (amount > 0),
    currency               TEXT        NOT NULL,

    normalized_status      TEXT        NOT NULL,
    gateway_status         TEXT        NOT NULL DEFAULT '',
    fraud_status           TEXT        NOT NULL DEFAULT '',
    status_rank            SMALLINT    NOT NULL DEFAULT 0,

    payment_method         TEXT        NOT NULL DEFAULT '',
    payment_type           TEXT        NOT NULL DEFAULT '',

    snap_token             TEXT,
    snap_redirect_url      TEXT,

    refunded_amount        BIGINT      NOT NULL DEFAULT 0 CHECK (refunded_amount >= 0),

    metadata               JSONB       NOT NULL DEFAULT '{}'::jsonb,
    gateway_options        JSONB       NOT NULL DEFAULT '{}'::jsonb,
    gateway_data           JSONB       NOT NULL DEFAULT '{}'::jsonb,

    expires_at             TIMESTAMPTZ,
    paid_at                TIMESTAMPTZ,
    canceled_at            TIMESTAMPTZ,
    expired_at             TIMESTAMPTZ,
    refunded_at            TIMESTAMPTZ,
    last_synced_at         TIMESTAMPTZ,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- One application order id maps to exactly one payment (PRD §61).
CREATE UNIQUE INDEX payments_application_order_key
    ON payments (application_id, application_order_id);

CREATE INDEX payments_application_created_idx ON payments (application_id, created_at DESC);
CREATE INDEX payments_status_idx ON payments (normalized_status, created_at DESC);
CREATE INDEX payments_gateway_transaction_idx ON payments (gateway, gateway_transaction_id);
CREATE INDEX payments_created_at_idx ON payments (created_at DESC);

CREATE TABLE payment_customers (
    payment_id       TEXT PRIMARY KEY REFERENCES payments (id) ON DELETE CASCADE,
    first_name       TEXT  NOT NULL DEFAULT '',
    last_name        TEXT  NOT NULL DEFAULT '',
    email            TEXT  NOT NULL DEFAULT '',
    phone            TEXT  NOT NULL DEFAULT '',
    billing_address  JSONB,
    shipping_address JSONB
);

CREATE TABLE payment_items (
    id          TEXT PRIMARY KEY,
    payment_id  TEXT     NOT NULL REFERENCES payments (id) ON DELETE CASCADE,
    position    INTEGER  NOT NULL,
    sku         TEXT     NOT NULL DEFAULT '',
    name        TEXT     NOT NULL,
    price       BIGINT   NOT NULL,
    quantity    INTEGER  NOT NULL CHECK (quantity > 0),
    category    TEXT     NOT NULL DEFAULT '',
    merchant    TEXT     NOT NULL DEFAULT '',
    url         TEXT     NOT NULL DEFAULT ''
);

CREATE UNIQUE INDEX payment_items_position_key ON payment_items (payment_id, position);

-- ---------------------------------------------------------------------------
-- Idempotency (PRD §63)
-- ---------------------------------------------------------------------------

CREATE TABLE idempotency_keys (
    id             TEXT PRIMARY KEY,
    application_id TEXT        NOT NULL REFERENCES applications (id) ON DELETE CASCADE,
    idempotency_key TEXT       NOT NULL,
    endpoint       TEXT        NOT NULL,
    -- Hash of the canonical request so a reused key with a different body can
    -- be rejected rather than silently returning the wrong response.
    request_hash   TEXT        NOT NULL,
    state          TEXT        NOT NULL CHECK (state IN ('in_progress', 'completed')),
    payment_id     TEXT        REFERENCES payments (id) ON DELETE SET NULL,
    response_status INTEGER,
    response_body  JSONB,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at   TIMESTAMPTZ,
    expires_at     TIMESTAMPTZ NOT NULL
);

CREATE UNIQUE INDEX idempotency_keys_scope_key
    ON idempotency_keys (application_id, endpoint, idempotency_key);
CREATE INDEX idempotency_keys_expires_at_idx ON idempotency_keys (expires_at);

-- ---------------------------------------------------------------------------
-- Gateway-side transaction state and raw inbound notifications
-- ---------------------------------------------------------------------------

CREATE TABLE gateway_transactions (
    id                     TEXT PRIMARY KEY,
    payment_id             TEXT        NOT NULL REFERENCES payments (id) ON DELETE CASCADE,
    gateway                TEXT        NOT NULL,
    gateway_transaction_id TEXT        NOT NULL,
    gateway_order_id       TEXT        NOT NULL,
    gateway_status         TEXT        NOT NULL DEFAULT '',
    fraud_status           TEXT        NOT NULL DEFAULT '',
    payment_type           TEXT        NOT NULL DEFAULT '',
    gross_amount           BIGINT,
    currency               TEXT        NOT NULL DEFAULT '',
    transaction_time       TIMESTAMPTZ,
    settlement_time        TIMESTAMPTZ,
    raw_payload            JSONB       NOT NULL DEFAULT '{}'::jsonb,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX gateway_transactions_identity_key
    ON gateway_transactions (gateway, gateway_transaction_id);
CREATE INDEX gateway_transactions_payment_idx ON gateway_transactions (payment_id);

-- Every inbound notification is persisted, including ones PayMux cannot route,
-- so nothing is silently discarded (PRD §91 rule 15).
CREATE TABLE gateway_events (
    id                     TEXT PRIMARY KEY,
    gateway                TEXT        NOT NULL,
    gateway_account_id     TEXT        REFERENCES gateway_accounts (id) ON DELETE SET NULL,
    payment_id             TEXT        REFERENCES payments (id) ON DELETE SET NULL,
    application_id         TEXT        REFERENCES applications (id) ON DELETE SET NULL,
    gateway_order_id       TEXT        NOT NULL DEFAULT '',
    gateway_transaction_id TEXT        NOT NULL DEFAULT '',
    gateway_status         TEXT        NOT NULL DEFAULT '',
    fraud_status           TEXT        NOT NULL DEFAULT '',
    -- Stable hash over the gateway's identifying fields; the uniqueness
    -- constraint is what makes duplicate notifications harmless (PRD §39).
    dedupe_key             TEXT        NOT NULL,
    signature_verified     BOOLEAN     NOT NULL DEFAULT FALSE,
    routing_status         TEXT        NOT NULL
        CHECK (routing_status IN ('routed', 'duplicate', 'unrouted', 'rejected', 'ignored')),
    routing_error          TEXT        NOT NULL DEFAULT '',
    payload                JSONB       NOT NULL DEFAULT '{}'::jsonb,
    received_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    processed_at           TIMESTAMPTZ
);

CREATE UNIQUE INDEX gateway_events_dedupe_key ON gateway_events (gateway, dedupe_key);
CREATE INDEX gateway_events_payment_idx ON gateway_events (payment_id, received_at DESC);
CREATE INDEX gateway_events_received_idx ON gateway_events (received_at DESC);
CREATE INDEX gateway_events_routing_status_idx ON gateway_events (routing_status, received_at DESC);

-- ---------------------------------------------------------------------------
-- Refunds and subscriptions
-- ---------------------------------------------------------------------------

CREATE TABLE refunds (
    id                TEXT PRIMARY KEY,
    payment_id        TEXT        NOT NULL REFERENCES payments (id) ON DELETE CASCADE,
    application_id    TEXT        NOT NULL REFERENCES applications (id) ON DELETE RESTRICT,
    gateway_refund_id TEXT,
    refund_key        TEXT,
    amount            BIGINT      NOT NULL CHECK (amount > 0),
    currency          TEXT        NOT NULL,
    reason            TEXT        NOT NULL DEFAULT '',
    status            TEXT        NOT NULL,
    gateway_status    TEXT        NOT NULL DEFAULT '',
    failure_reason    TEXT        NOT NULL DEFAULT '',
    raw_response      JSONB       NOT NULL DEFAULT '{}'::jsonb,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX refunds_payment_idx ON refunds (payment_id, created_at DESC);
CREATE INDEX refunds_application_idx ON refunds (application_id, created_at DESC);
-- The gateway's refund key, when supplied, must be unique per payment so a
-- retried refund request cannot create two refunds.
CREATE UNIQUE INDEX refunds_payment_refund_key ON refunds (payment_id, refund_key)
    WHERE refund_key IS NOT NULL;

CREATE TABLE subscriptions (
    id                      TEXT PRIMARY KEY,
    application_id          TEXT        NOT NULL REFERENCES applications (id) ON DELETE RESTRICT,
    gateway_account_id      TEXT        NOT NULL REFERENCES gateway_accounts (id) ON DELETE RESTRICT,
    gateway                 TEXT        NOT NULL,
    gateway_subscription_id TEXT,
    name                    TEXT        NOT NULL,
    amount                  BIGINT      NOT NULL CHECK (amount > 0),
    currency                TEXT        NOT NULL,
    status                  TEXT        NOT NULL,
    gateway_status          TEXT        NOT NULL DEFAULT '',
    interval_unit           TEXT        NOT NULL DEFAULT '',
    interval_count          INTEGER     NOT NULL DEFAULT 1,
    max_interval            INTEGER,
    start_time              TIMESTAMPTZ,
    payment_type            TEXT        NOT NULL DEFAULT '',
    -- Gateway payment token. Never a raw card number (PRD §35).
    payment_token           TEXT        NOT NULL DEFAULT '',
    metadata                JSONB       NOT NULL DEFAULT '{}'::jsonb,
    gateway_data            JSONB       NOT NULL DEFAULT '{}'::jsonb,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX subscriptions_application_idx ON subscriptions (application_id, created_at DESC);
CREATE UNIQUE INDEX subscriptions_gateway_id_key
    ON subscriptions (gateway, gateway_subscription_id)
    WHERE gateway_subscription_id IS NOT NULL;

-- ---------------------------------------------------------------------------
-- Normalized PayMux events
-- ---------------------------------------------------------------------------

CREATE TABLE events (
    id               TEXT PRIMARY KEY,
    sequence         BIGSERIAL   NOT NULL,
    application_id   TEXT        NOT NULL REFERENCES applications (id) ON DELETE CASCADE,
    type             TEXT        NOT NULL,
    gateway          TEXT        NOT NULL,
    payment_id       TEXT        REFERENCES payments (id) ON DELETE SET NULL,
    refund_id        TEXT        REFERENCES refunds (id) ON DELETE SET NULL,
    subscription_id  TEXT        REFERENCES subscriptions (id) ON DELETE SET NULL,
    gateway_event_id TEXT        REFERENCES gateway_events (id) ON DELETE SET NULL,
    -- Identifies the real-world occurrence this event reports. Two events with
    -- the same key describe the same thing, so the second is a duplicate.
    dedupe_key       TEXT,
    payload          JSONB       NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX events_application_idx ON events (application_id, created_at DESC);
CREATE INDEX events_payment_idx ON events (payment_id, created_at DESC);
CREATE INDEX events_type_idx ON events (type, created_at DESC);
CREATE INDEX events_sequence_idx ON events (sequence);

-- Publishing is idempotent: a redelivered notification for a state PayMux has
-- already announced cannot produce a second downstream event. The key is
-- chosen by the publisher so that genuinely distinct occurrences — successive
-- partial refunds, for instance — still get their own event.
CREATE UNIQUE INDEX events_dedupe_key ON events (dedupe_key)
    WHERE dedupe_key IS NOT NULL;

-- ---------------------------------------------------------------------------
-- Webhook deliveries
--
-- This table doubles as the durable job queue: workers claim rows with
-- FOR UPDATE SKIP LOCKED, which keeps enqueueing transactional with the event
-- that caused it and needs no extra infrastructure (PRD §9, §71).
-- ---------------------------------------------------------------------------

CREATE TABLE deliveries (
    id               TEXT PRIMARY KEY,
    event_id         TEXT        NOT NULL REFERENCES events (id) ON DELETE CASCADE,
    application_id   TEXT        NOT NULL REFERENCES applications (id) ON DELETE CASCADE,
    destination_id   TEXT        NOT NULL REFERENCES webhook_destinations (id) ON DELETE CASCADE,
    url              TEXT        NOT NULL,
    state            TEXT        NOT NULL
        CHECK (state IN ('pending', 'delivering', 'succeeded', 'failed', 'dead', 'canceled')),
    attempt_count    INTEGER     NOT NULL DEFAULT 0,
    max_attempts     INTEGER     NOT NULL DEFAULT 7,
    next_attempt_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_attempt_at  TIMESTAMPTZ,
    last_status_code INTEGER,
    last_error       TEXT        NOT NULL DEFAULT '',
    last_duration_ms INTEGER,
    locked_at        TIMESTAMPTZ,
    locked_by        TEXT,
    succeeded_at     TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- One delivery per event and destination, so a replayed enqueue is a no-op.
CREATE UNIQUE INDEX deliveries_event_destination_key ON deliveries (event_id, destination_id);

-- The worker's claim query: pending/failed rows that are due, oldest first.
CREATE INDEX deliveries_due_idx ON deliveries (next_attempt_at)
    WHERE state IN ('pending', 'failed');

CREATE INDEX deliveries_application_idx ON deliveries (application_id, created_at DESC);
CREATE INDEX deliveries_state_idx ON deliveries (state, created_at DESC);
CREATE INDEX deliveries_event_idx ON deliveries (event_id);
-- Lets the worker recover deliveries abandoned by a crashed process.
CREATE INDEX deliveries_locked_idx ON deliveries (locked_at) WHERE state = 'delivering';

CREATE TABLE delivery_attempts (
    id             TEXT PRIMARY KEY,
    delivery_id    TEXT        NOT NULL REFERENCES deliveries (id) ON DELETE CASCADE,
    attempt_number INTEGER     NOT NULL,
    status_code    INTEGER,
    error          TEXT        NOT NULL DEFAULT '',
    duration_ms    INTEGER     NOT NULL DEFAULT 0,
    -- Truncated and never trusted for control flow; useful for debugging.
    response_body  TEXT        NOT NULL DEFAULT '',
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX delivery_attempts_number_key ON delivery_attempts (delivery_id, attempt_number);
CREATE INDEX delivery_attempts_delivery_idx ON delivery_attempts (delivery_id, created_at DESC);

-- ---------------------------------------------------------------------------
-- Audit log
-- ---------------------------------------------------------------------------

CREATE TABLE audit_logs (
    id          TEXT PRIMARY KEY,
    actor_type  TEXT        NOT NULL CHECK (actor_type IN ('admin', 'application', 'system')),
    actor_id    TEXT        NOT NULL DEFAULT '',
    action      TEXT        NOT NULL,
    target_type TEXT        NOT NULL DEFAULT '',
    target_id   TEXT        NOT NULL DEFAULT '',
    request_id  TEXT        NOT NULL DEFAULT '',
    ip_address  TEXT        NOT NULL DEFAULT '',
    metadata    JSONB       NOT NULL DEFAULT '{}'::jsonb,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX audit_logs_created_idx ON audit_logs (created_at DESC);
CREATE INDEX audit_logs_target_idx ON audit_logs (target_type, target_id, created_at DESC);
CREATE INDEX audit_logs_actor_idx ON audit_logs (actor_type, actor_id, created_at DESC);
